apiVersion: batch/v1
kind: Job
metadata:
  name: create-deployment-job1
spec:
  template:
    spec:
      containers:
      - name: deployment-creator1
        image: bitnami/kubectl:latest  # Use an image with kubectl installed
        command:
          - /bin/sh
          - -c
          - |
            # Define the deployment YAML inline and create the deployment
            cat <<EOF | kubectl apply -f -
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: example-deployment1
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: example
              template:
                metadata:
                  labels:
                    app: example
                spec:
                  containers:
                  - name: example-container1
                    image: nginx:latest
            EOF
      restartPolicy: Never
  backoffLimit: 4  # Number of retries if the Job fails
