apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-env
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret1111
                  key: password
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret1111
                  key: username
          ports:
            - containerPort: 80
