apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1111
  namespace: guestbook
  labels:
    app: nginx
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        envFrom:
        - secretRef:
            name: test-secret
        ports:
        - containerPort: 80
