apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-vol
  namespace: guestbook
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: mypod
        image: nginx:1.14.2
        volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
          readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: mysecret
          optional: false # default setting; "mysecret" must exist
