apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-volume
  namespace: guestbook
  labels:
    app: nginx
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: dotfile-secret
  containers:
  - name: nginx-test-container
    image: nginx:1.14.2
    command:
    - ls
    - "-l"
    - "/etc/secret-volume"
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"
