apiVersion: v1
kind: Pod
metadata:
  name: envfrom-secret
spec:
  containers:
  - name: envars-test-container
    image: nginx:1.14.2
    command: [ "ls" ]
    envFrom:
    - secretRef:
        name: test-secret
