apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
      - name: nginx
        image: nginx:1.14.2
        envFrom:
        - secretRef:
            name: test-secret
        ports:
        - containerPort: 80
