apiVersion: v1
kind: Pod
metadata:
  name: envfrom-secret
  namespace: guestbook
spec:
  containers:
  - name: envars-test-container
    image: nginx:1.14.2
    envFrom:
    - secretRef:
        name: test-secret
