apiVersion: v1
kind: Pod
metadata:
  name: envfrom-secret
spec:
  containers:
  - name: envars-test-container
    image: nginx:1.14.2
    command: [ "/bin/sh", "-c", "env" ]
    envFrom:
    - secretRef:
        name: test-secret
