apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
spec:
  containers:
    - name: nginx-container
      image: nginx:1.14.2
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: db-password
  restartPolicy: Never
